/* Generated By:JavaCC: Do not edit this line. PatternParserConstants.java */
package org.vanb.viva.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PatternParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 5;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 6;
  /** RegularExpression Id. */
  int HEX_LITERAL = 7;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 8;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 9;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 10;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 11;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 12;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 13;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 14;
  /** RegularExpression Id. */
  int STRING_LITERAL = 15;
  /** RegularExpression Id. */
  int DOUBLE = 16;
  /** RegularExpression Id. */
  int INTEGER = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int LONG = 19;
  /** RegularExpression Id. */
  int FLOAT = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;
  /** RegularExpression Id. */
  int LETTER = 23;
  /** RegularExpression Id. */
  int PART_LETTER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"double\"",
    "\"integer\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"string\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"{\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"}\"",
    "\";\"",
    "\"*\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"||\"",
    "\"&&\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"#\"",
    "\"$\"",
  };

}
