/* Generated By:JavaCC: Do not edit this line. PatternParser.java */
package org.vanb.viva.parser;

import org.vanb.viva.patterns.*;
import org.vanb.viva.expressions.*;
import org.vanb.viva.utils.*;

public class PatternParser implements PatternParserConstants {
    private SymbolTable<Class<?>> symbols = new SymbolTable<Class<?>>();

  final public PatternList multilinePattern() throws ParseException {
    PatternList plist = new PatternList();
    Pattern p;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case 19:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      p = singlePattern();
          plist.addPattern( p );
    }
      {if (true) return plist;}
    throw new Error("Missing return statement in function");
  }

  final public Pattern singlePattern() throws ParseException {
    Pattern pattern;
    PatternListController controller;
    PatternList plist;
    ExpressionNode exp=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 19:
      jj_consume_token(19);
      jj_consume_token(20);
      controller = qualifier();
      jj_consume_token(21);
                                         symbols.addLevel();
      plist = multilinePattern();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 20:
        jj_consume_token(20);
        exp = constraint(true);
        jj_consume_token(21);
        break;
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      jj_consume_token(22);
        symbols.removeLevel();
        controller.setPatternList( plist );
        if( exp!=null ) controller.addConstraint( exp );
        pattern = controller;
      break;
    case IDENTIFIER:
      plist = simplePattern();
      jj_consume_token(23);
        controller = new SingleLineController();
        controller.setPatternList( plist );
        pattern = controller;
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return pattern;}
    throw new Error("Missing return statement in function");
  }

  final public PatternListController qualifier() throws ParseException {
    PatternListController pattern=null;
    Pattern term=null;
    ExpressionNode exp = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 24:
      jj_consume_token(24);
      exp = expression(false);
        CountController count = new CountController();
        count.setCountExpression( exp );
        pattern = count;
      break;
    case 25:
      jj_consume_token(25);
         symbols.addLevel();
      term = simplePattern();
        symbols.removeLevel();
        MatchController match = new MatchController();
        match.setTerminatingPattern( term );
        pattern = match;
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return pattern;}
    throw new Error("Missing return statement in function");
  }

  final public PatternList simplePattern() throws ParseException {
    PatternList plist = new PatternList();
    ExpressionNode exp = null;
    Token token;
    label_2:
    while (true) {
      token = jj_consume_token(IDENTIFIER);
          String name = token.image;
          boolean unique = symbols.add( name, Integer.class );
          if( !unique )
          {
              {if (true) throw new ParseException( "Variable " + name + " is already defined." );}
          }
          IntegerPattern pattern = new IntegerPattern();
          plist.addPattern( pattern );
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        jj_consume_token(26);
        exp = constraint(false);
        jj_consume_token(27);
        break;
      default:
        jj_la1[4] = jj_gen;
        ;
      }
          if( exp!=null ) plist.addConstraint( exp );
          exp = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
    }
      {if (true) return plist;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionNode constraint(boolean isCumulative) throws ParseException {
    ExpressionNode lhs, rhs;
    BinaryOperatorNode op;
    lhs = orConstraint(isCumulative);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 28:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_3;
      }
      jj_consume_token(28);
      rhs = orConstraint(isCumulative);
          op = new OrNode();
          op.instantiate( lhs, rhs );
          lhs = op;
    }
      {if (true) return lhs;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionNode orConstraint(boolean isCumulative) throws ParseException {
    ExpressionNode lhs, rhs;
    BinaryOperatorNode op;
    lhs = simpleConstraint(isCumulative);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 29:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      jj_consume_token(29);
      rhs = simpleConstraint(isCumulative);
          op = new AndNode();
          op.instantiate( lhs, rhs );
          lhs = op;
    }
      {if (true) return lhs;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionNode simpleConstraint(boolean isCumulative) throws ParseException {
    ExpressionNode lhs, rhs;
    BinaryOperatorNode op, newop;
    lhs = expression(isCumulative);
    op = boolop();
    rhs = expression(isCumulative);
      op.instantiate( lhs, rhs );
      lhs = rhs;
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 25:
      case 30:
      case 31:
      case 32:
      case 33:
      case 34:
      case 35:
      case 36:
      case 37:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_5;
      }
      newop = boolop();
      rhs = expression(isCumulative);
              newop.instantiate( lhs, rhs );
              BinaryOperatorNode andop = new AndNode();
              andop.instantiate( op, newop );
              op = andop;
              lhs = rhs;
    }
      {if (true) return op;}
    throw new Error("Missing return statement in function");
  }

  final public BinaryOperatorNode boolop() throws ParseException {
    BinaryOperatorNode op = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 30:
      jj_consume_token(30);
            op = new GreaterThanNode();
      break;
    case 31:
      jj_consume_token(31);
            op = new LessThanNode();
      break;
    case 32:
      jj_consume_token(32);
             op = new GreaterThanEqualToNode();
      break;
    case 33:
      jj_consume_token(33);
             op = new LessThanEqualToNode();
      break;
    case 25:
      jj_consume_token(25);
            op = new EqualToNode();
      break;
    case 34:
      jj_consume_token(34);
             op = new EqualToNode();
      break;
    case 35:
      jj_consume_token(35);
             op = new NotEqualToNode();
      break;
    case 36:
      jj_consume_token(36);
             op = new NotEqualToNode();
      break;
    case 37:
      jj_consume_token(37);
             op = new EqualToNode();
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
        {if (true) return op;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionNode expression(boolean isCumulative) throws ParseException {
    ExpressionNode lhs, rhs;
    BinaryOperatorNode op;
    lhs = term(isCumulative);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 38:
      case 39:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      op = addop();
      rhs = term(isCumulative);
          op.instantiate( lhs, rhs );
          lhs = op;
    }
      {if (true) return lhs;}
    throw new Error("Missing return statement in function");
  }

  final public BinaryOperatorNode addop() throws ParseException {
    BinaryOperatorNode op = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 38:
      jj_consume_token(38);
          op = new PlusNode();
      break;
    case 39:
      jj_consume_token(39);
          op = new MinusNode();
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return op;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionNode term(boolean isCumulative) throws ParseException {
    ExpressionNode lhs, rhs;
    BinaryOperatorNode op;
    lhs = factor(isCumulative);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 24:
      case 40:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_7;
      }
      op = multop();
      rhs = factor(isCumulative);
          op.instantiate( lhs, rhs );
          lhs = op;
    }
      {if (true) return lhs;}
    throw new Error("Missing return statement in function");
  }

  final public BinaryOperatorNode multop() throws ParseException {
    BinaryOperatorNode op = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 24:
      jj_consume_token(24);
          op = new TimesNode();
      break;
    case 40:
      jj_consume_token(40);
          op = new DivideNode();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return op;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionNode factor(boolean isCumulative) throws ParseException {
    Token token;
    ExpressionNode node;
    Object value;
    String lit;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      token = jj_consume_token(IDENTIFIER);
        String name = token.image;
        Class<?> type = symbols.lookup( name );
        if( type==null )
        {
            {if (true) throw new ParseException( "Unknown identifier: " + name );}
        }
        node = new VariableNode( name, type );
      break;
    case INTEGER_LITERAL:
      token = jj_consume_token(INTEGER_LITERAL);
        boolean islong = token.image.toUpperCase().endsWith( "L" );
        try
        {
            if( islong )
            {
                value = new Long( token.image );
            }
            else
            {
                value = new Integer( token.image );
            }
        }
        catch( Exception e )
        {
            {if (true) throw new ParseException( "Unable to parse " + token.image
                + " as a " + (islong ? "Long" : "Integer") );}
        }

        node = new ConstantNode( value );
      break;
    case FLOATING_POINT_LITERAL:
      token = jj_consume_token(FLOATING_POINT_LITERAL);
        try
        {
            value = new Double( token.image );
        }
        catch( Exception e )
        {
            {if (true) throw new ParseException( "Unable to parse " + token.image + " as a Double" );}
        }
        node = new ConstantNode( value );
      break;
    case CHARACTER_LITERAL:
      token = jj_consume_token(CHARACTER_LITERAL);
        lit = token.image;
        if( lit.startsWith( "'" ) ) lit = lit.substring(1);
        value = new Integer( (int)(lit.charAt(0)) );
        node = new ConstantNode( value );
      break;
    case STRING_LITERAL:
      token = jj_consume_token(STRING_LITERAL);
        lit = token.image;
        if( lit.startsWith( "\u005c"" ) ) lit = lit.substring(1);
        if( lit.endsWith( "\u005c"" ) ) lit = lit.substring( 0, lit.length()-1);
        node = new ConstantNode( lit );
      break;
    case 26:
      jj_consume_token(26);
      node = expression(isCumulative);
      jj_consume_token(27);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return node;}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public PatternParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[15];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x90000,0x100000,0x90000,0x3000000,0x4000000,0x10000,0x10000000,0x20000000,0xc2000000,0xc2000000,0x0,0x0,0x1000000,0x1000000,0x401c220,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3f,0x3f,0xc0,0xc0,0x100,0x100,0x0,};
   }

  /** Constructor with InputStream. */
  public PatternParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public PatternParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new PatternParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public PatternParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new PatternParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public PatternParser(PatternParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(PatternParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[41];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 15; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 41; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
